

install:
	mkdir -p /usr/share/maliit/plugins/com/jolla/layouts
	cp hy.conf hy.qml /usr/share/maliit/plugins/com/jolla/layouts/
	cp hy-phonetic.conf hy-phonetic.qml /usr/share/maliit/plugins/com/jolla/layouts/

all: install
